mint-o-badges/badgr-server

.docker/Dockerfile.dev.api, .docker/Dockerfile.prod.api, README.md, docker-compose.yml, requirements.txt
- Pin docker image to specific version
- Add platform for Apple Silicon based Mac
- Pin `importlib-resources` package. The by default installed version is not working
=> (fix): update local development docker image

.docker/Dockerfile.prod.api, .docker/etc/uwsgi.ini, docker-compose.prod.yml, requirements.txt
- docker multi stage build
- lockdown user with least privileges
- use virtualenv
=> (chore): docker best pratices

.docker/Dockerfile.dev.api, README.md, apps/badgrsocialauth/providers/facebook/tests.py, apps/badgrsocialauth/urls.py, apps/issuer/tests/test_assertion.py, apps/issuer/tests/test_badgeclass.py, apps/issuer/tests/test_issuer.py, apps/mainsite/settings_tests.py, apps/mainsite/settings_testserver.py, docker-compose.yml, requirements.txt
Mainly added necessary fields, removed some old tests and added instructions on how to run server tests.
=> server: Get tests to run

apps/mainsite/templates/email/base.html
There's an error due to using a variable block many times.
=> bug-fix in email template

deploy.sh
Add script to automate deployment
=> Automate production deployment

apps/backpack/api_v1.py, apps/issuer/models.py
Add parentheses to prevent this kind of problem
=> Issuer cant be edited on empty address

apps/mainsite/views.py
=> fix nounproject query

apps/mainsite/models.py
Don't double https with invalid cors configuration
=> Register confirm link is broken

apps/issuer/helpers.py, apps/issuer/managers.py, apps/issuer/serializers_v1.py, apps/issuer/tasks.py, apps/mainsite/settings.py
Removed all the badgerank stuff since this service doesn't exist and it caused problems on prod (I have no idea why *only* on prod).
=> Fix badge creation 504

apps/mainsite/views.py
=> Create badge: AI-Tool doesn't work #160

apps/mainsite/templates/admin/base_site.html, apps/mainsite/templates/issuer/email/notify_account_holder_message.html, apps/mainsite/templates/issuer/email/notify_earner_message.html, apps/mainsite/templates/public/base.html, apps/mainsite/templates/rest_framework/api.html
This PR fixes the error occurred when trying to award a badge.
Ticket: https://github.com/orgs/mint-o-badges/projects/2/views/1?pane=issue&itemId=60212030
=> fix: awarding badges is not working

apps/mainsite/templates/admin/base_site.html
This PR fixes the error raised when opening staff page.
=> fix: staff page not working

apps/backpack/views.py
Only allow recipient of the badge to request the pdf
=> fix: pdf permissions

apps/backpack/views.py, apps/mainsite/account_adapter.py
* feat: rework competencies in pdf
* fix: link
=> New Release - fix display of competency duration in pdf

apps/mainsite/oauth2_api.py
=> fix: external oauth error

apps/issuer/serializers_v1.py
change needed for new insti cards to display the count of learning path an issuer has
=> feat: set learning path count

apps/issuer/models.py, apps/issuer/public_api.py, apps/issuer/serializers_v1.py
Include orgImg for badge editing. 
_TODO_: include orgImg only on the badge editing page
=> feat: include orgImg

docker-compose.yml
change in memcached that is needed to allow for bigger files to be uploaded 
https://github.com/mint-o-badges/badgr-ui/pull/842/
partly closes [#808](https://github.com/mint-o-badges/badgr-ui/issues/808)
=> feat: change memcache settings to allow for bigger images

docker-compose.yml
cache needs to be increased to handle larger images in the file upload
=> increase mem size to allow bigger images to be uploaded

apps/mainsite/oauth2_api.py
fix: only remove token if present
=> Moodle Plugin key error

README.md, docker-compose.debug.yml
As discussed a couple of things I noticed during going through the README while setting up my environment.
=> Update README to include some findings during initial setup

apps/issuer/models.py
django linter ran hence the many changes that I had to resolve
part of mint-o-badges/badgr-ui#1109
=> feat: include slug in json response for badge assertions

apps/issuer/api.py, apps/issuer/public_api_urls.py
* Fix/remove old blocks in email (#379)
* fix: remove faq and mbr block
* fix: dont underline non-link
* feat: adjust spacing
* feat: email text and style adjustements
* fix: dont underline whitespace (#380)
* fix: merge conflicts (#391)
* fix: allow dot in search
* fix: id
---------
=> Fix/issuer staff flow (#394)

apps/issuer/public_api.py
This PR will redirect users to the default badgrapps 'not-found' collections route, when they request a collection that is not public.
Additionally, when the UI requests the json of a collection and the collection happens to not be public, a HTTP status code of 204 (No Content) is returned instead of a 404.
The corresponding changes in the UI will make sure to show the contents of the 'not-found' route for this case as well.
=> feat: redirect private collections to badgrapp

apps/issuer/__init__.py, apps/issuer/apps.py, apps/issuer/jsonld_loader.py
Adds custom document loader to cache jsonld-contexts to avoid hitting the rate-limit of W3C
=> feat: cache contexts in jsonld loader

.github/workflows/release.yml
Also note the [UI](https://github.com/mint-o-badges/badgr-ui/pull/1499)
=> feat: create release (notes) on merge to production

apps/issuer/management/commands/recalculate_private_keys.py
* fix: force recreate to get new json
* fix: variable
=> fix: force recreate to get new json (#522)

apps/issuer/models.py
**I did not test this yet!**
I don't know how to (safely) rebake badges and check the result. This change *should* work, but if you review it, please test it / explain to me how I can test it.
=> fix: attach directory in rebaking

apps/mainsite/badge_pdf.py
* fix: use cairosvg instead of renderPM for svg conversion
* fix: rm unused import
=> fix: use cairosvg instead of renderPM for svg conversion (#540)

apps/issuer/management/commands/count_badges.py
* feat: add command to count badges and assertions
* fix: remove naming of error
---------
=> feat: add command to count badges and assertions (#550)
